baseurl = "https://example.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "custom"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "gaths-blog"
    subtitle = "gath's blog and porfolio"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "gath"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "ğŸ˜about"
        url = "/about"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "ğŸ“blog"
        url = "/posts"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "games"
        name = "ğŸ®games"
        url = "/games"
        weight = 2